services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ""
        HTTPS_PROXY: ""
    image: zhumakom/pandas_reports-app:1.0.0
    ports:
      - "5000:5000"
    depends_on:
      - qdrant
    environment:
      - ALLURE_API=http://10.15.132.171:8080/api
      - QDRANT_URL=http://qdrant:6333
      - ALLURE_USER=hulk
      - ALLURE_PASS=hulkQA
    volumes:
      - ./:/app
    command: >
      uvicorn main:app
        --host 0.0.0.0
        --port 5000

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
